version: '3'
services:
    node1:
        build:
            dockerfile: ./docker/app.dockerfile
            context: .
        image: pontalti/cs
        container_name: cs
        ports:
          - "8080:8080"
          - "8000:8000"
        networks: 
            - production-network

networks: 
    production-network:
        driver: bridge